[package]
name = "narfmap"
version = "1.4.0"
edition = "2018"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
cxx = "1.0"

[build-dependencies]
miette = { version = "5", features = ["fancy"] } # optional but gives nicer error messages!
bindgen = "0.65.1"
